[mysql]
master="aduser:eOWIN2H3lWqJFmQE9n8P@tcp(adserverdb.c16aoo6syncd.us-west-1.rds.amazonaws.com:3306)/ad_server?charset=utf8mb4&parseTime=true&loc=Local"
use_master_slave=false

[redis]
ip = "redis"
port = 6379

[queue]
ip = "redis"
port = 6379

[ton_network.testnet]
rpc_url = "https://data-seed-prebsc-1-s1.binance.org:8545"
chain_id = "97"
address = "0QDbvL_4w6cZE8buKiRpH8jyA3D5xWXmXXSVycgdXamslUx3"

[ton_network.mainnet]
rpc_url = "https://bsc-dataseed.binance.org"
chain_id = "56"
address = "0QDbvL_4w6cZE8buKiRpH8jyA3D5xWXmXXSVycgdXamslUx3

[nats]
host="127.0.0.1"
port=4222
subjects = [
    "ad_info.tracerHash",
    "ad_info.get_ad",
    "ad_info.clickinfo",
    "ad_info.loginfo",
    "ad_info.ad_in_call",
    "ad_info.get_ad_miss"
]
consumer_name = "worker1"
use_jetstream = false

[hash]
get_ad=false
loginfo=false
clickinfo=true
tracer_hash=false
ad_in_call=false
get_ad_miss=false

[mongo]
ip = "mongo"
port = 27017


[global]
gamename = "leshusanguo"
version = "0.1"